using System.Drawing;
using ERP_Project1.Api;

namespace ERP_Project1
{
    /// <summary>
    /// Read-only: every pay run that has actually been paid. Payroll Records is where a run is
    /// created and corrected; once it is marked Paid it is locked, and this is where it lives
    /// afterwards as a permanent record.
    /// </summary>
    internal sealed class PayrollHistoryPage : CrudPageBase<PayrollDto>
    {
        private readonly Label _summary;

        public PayrollHistoryPage(FitCoreSession session)
            : base(session, "Payroll History", "Every pay run that has been marked Paid.",
                   "paid run", "Employee name or code")
        {
            AddAction("View receipt", ButtonTone.Secondary, () => ShowReceiptAsync(), 116);

            _summary = new Label
            {
                AutoSize = true,
                Font = UiTheme.Small,
                ForeColor = UiTheme.TextMuted,
                Margin = new Padding(16, 10, 0, 0),
                UseMnemonic = false
            };
            FilterBar.Controls.Add(_summary);
        }

        protected override bool SupportsAdd => false;
        protected override bool SupportsEdit => false;
        protected override bool SupportsDelete => false;

        protected override string EmptyHeadline => "No paid runs yet";
        protected override string EmptyDetail =>
            "Once a pay run is marked Paid on Payroll Records, it appears here.";

        protected override async Task<List<PayrollDto>?> FetchAsync()
        {
            var all = Unwrap(await Session.Payroll.GetAllAsync());
            return all?.Where(p => string.Equals(p.Status, "Paid", StringComparison.OrdinalIgnoreCase))
                       .OrderByDescending(p => p.PaidDate)
                       .ToList();
        }

        protected override void DefineColumns()
        {
            Column(nameof(PayrollDto.EmployeeName), "Employee", 140);
            DateColumn(nameof(PayrollDto.PeriodStart), "From", 75);
            DateColumn(nameof(PayrollDto.PeriodEnd), "To", 75);
            DateColumn(nameof(PayrollDto.PaidDate), "Paid on", 80);
            MoneyColumn(nameof(PayrollDto.GrossPay), "Gross", 80);
            MoneyColumn(nameof(PayrollDto.Deductions), "Deductions", 80);
            MoneyColumn(nameof(PayrollDto.NetPay), "Net", 80);
            Column(nameof(PayrollDto.ProcessedBy), "Generated by", 100);
        }

        protected override bool Matches(PayrollDto p, string term) =>
            (p.EmployeeName ?? "").Contains(term, StringComparison.OrdinalIgnoreCase) ||
            (p.EmployeeCode ?? "").Contains(term, StringComparison.OrdinalIgnoreCase);

        protected override void AfterLoad()
        {
            _summary.Text = $"{Items.Count:N0} paid run(s)      total paid {UiKit.Money(Items.Sum(p => p.NetPay))}";
        }

        private Task ShowReceiptAsync()
        {
            var p = Selected;
            if (p is null) { ShowError("Select a pay run to view its payslip."); return Task.CompletedTask; }

            ReceiptDialog.Show(this, ReceiptBuilder.ForPayroll(Session, p));
            return Task.CompletedTask;
        }
    }
}
